# Generated by Django 5.1 on 2024-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('borrowed', models.BooleanField(default=False)),
                ('borrow_date', models.DateField(default=None, null=True)),
                ('borrower', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
